#!/usr/bin/env bash
#Displays To infinity and beyond
#And Im Invinsible when it recieves a sigterm signal
while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
